#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"

uint2 ViewRectMin;
uint2 ViewRectMax;

uint SurfelBudget;
float SurfelRadius;

RWStructuredBuffer<uint> SurfelCount;
RWStructuredBuffer<float4> SurfelPositionAndRadius;
RWStructuredBuffer<float4> SurfelNormalAndFlags;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
    uint2 PixelPos = min(ViewRectMin + DispatchThreadId.xy, ViewRectMax - 1);

    // READ COVERAGE TEXTURE
    // Decide wheter TO continue or not based on Pos based on coverage texture
    // threshold of coverage
        // doesn't meet it return
    
    if (any(PixelPos >= ViewRectMax))
    {
        return;
    }
    
    int3 LoadPos = int3(PixelPos, 0);
    float DeviceZ = SceneDepthTexture.Load(LoadPos).r;

    // Skip the sky
    if (DeviceZ <= 0.0f)
    {
        return;
    }

    // Get Normal
    float4 GBufferA = GBufferATexture.Load(LoadPos);
    float3 WorldNormal = normalize(GBufferA.xyz * 2.0f - 1.0f);

    // Surfels persist across frames, but PrimaryView.PreViewTranslation shifts every
    // frame with the camera. Store world position
    float4 SvPosition = float4(PixelPos + 0.5f, DeviceZ, 1.0f);
    float3 TranslatedWorldPosition = SvPositionToTranslatedWorld(SvPosition);
    float3 WorldPosition = DFFastSubtractDemote(TranslatedWorldPosition, PrimaryView.PreViewTranslation);

    uint SurfelIndex;
    InterlockedAdd(SurfelCount[0], 1, SurfelIndex);

    if (SurfelIndex >= SurfelBudget)
    {
        InterlockedAdd(SurfelCount[0], -1);
        return;
    }
    
    // Scale surfel radius based on distance
    SurfelPositionAndRadius[SurfelIndex] = float4(WorldPosition, SurfelRadius);
    SurfelNormalAndFlags[SurfelIndex] = float4(WorldNormal, 0.0f);
}
