#include "/Engine/Public/Platform.ush"

RWStructuredBuffer<uint> SurfelCount;
RWStructuredBuffer<float4> SurfelPositionAndRadius;
RWStructuredBuffer<float4> SurfelNormalAndFlags;

uint SurfelBudget;
float SurfelRadius;

RWStructuredBuffer<uint> GridCellEntries;
RWStructuredBuffer<uint> GridCounter;

float3 GridPosition;
uint GridCellCount;
uint CellResolution;
uint CellCapacity;
uint CellSize;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
	// One thread per ALIVE surfel
	uint SurfelIdx = DispatchThreadId.x;
	if (SurfelIdx >= min(SurfelCount[0], SurfelBudget)) return;

	float4 PositionAndRadius = SurfelPositionAndRadius[SurfelIdx];
	float Radius = PositionAndRadius.w;

	// Local Position To Grid
	float3 LocalPosition = PositionAndRadius.xyz - GridPosition;
	
	int3 MaxIndex = int3((int)CellResolution - 1, (int)CellResolution - 1, (int)CellResolution - 1);
	
	// Conservative bounds (safe over-estimate)
	// How many grid widths does the disk cover? Clamp to grid bounds
	int3 MinimumLowCorner = max(int3(floor((LocalPosition - Radius) / CellSize)), int3(0, 0, 0));
	int3 MaximumHighCorner = min(int3(floor((LocalPosition + Radius) / CellSize)), MaxIndex);
	
	// Insert into every cell the surfel overlaps
	for (int z = MinimumLowCorner.z; z <= MaximumHighCorner.z; z++)
	for (int y = MinimumLowCorner.y; y <= MaximumHighCorner.y; y++)
	for (int x = MinimumLowCorner.x; x <= MaximumHighCorner.x; x++)
	{
		uint CellIdx = x + y * CellResolution + z * CellResolution * CellResolution;

		uint Slot;
		InterlockedAdd(GridCounter[CellIdx], 1u, Slot);
		
		// Every cell has a max amount of surfels it can hold
		if (Slot < CellCapacity)
		{
			GridCellEntries[CellIdx * CellCapacity + Slot] = SurfelIdx;
		}
	}
}
