#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"
#include "/Engine/Private/DeferredShadingCommon.ush"

RWTexture2D<float> CoverageTexture;

RWStructuredBuffer<uint> SurfelCount;
RWStructuredBuffer<float4> SurfelPositionAndRadius;
RWStructuredBuffer<float4> SurfelNormalAndFlags;

uint SurfelBudget;
float SurfelRadius;

RWStructuredBuffer<uint> GridCellEntries;
RWStructuredBuffer<uint> GridCounter;

float3 GridPosition;
uint GridCellCount;
uint CellResolution;
uint CellCapacity;
uint CellSize;

uint2 ViewRectMin;
uint2 ViewRectMax;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID)
{
	// TODO: can be dispatched per tile and use intrinsics
	uint2 PixelPos = min(ViewRectMin + DispatchThreadId.xy, ViewRectMax - 1);
	int3 LoadPos = int3(PixelPos, 0);
	
	// Get world surface normal and distance
	float4 GBufferA = GBufferATexture.Load(LoadPos);
	float3 WorldNormalAtPixel = normalize(GBufferA.xyz * 2.0f - 1.0f);
	
	float DeviceZ = SceneDepthTexture.Load(LoadPos).r;
	float4 SvPosition = float4(PixelPos + 0.5f, DeviceZ, 1.0f);
	float3 TranslatedWorldPosition = SvPositionToTranslatedWorld(SvPosition);
	float3 WorldPositionAtPixel = DFFastSubtractDemote(TranslatedWorldPosition, PrimaryView.PreViewTranslation);
	
	int3 PixelCell = int3(floor((WorldPositionAtPixel - GridPosition) / CellSize));
	bool bInsideGrid = all(PixelCell >= 0) && all(PixelCell < (int)CellResolution);

	if (bInsideGrid)
	{
		// Retrieve grid cell at this extracted world position 
		uint CellIdx = (uint)PixelCell.x
				+ (uint)PixelCell.y * CellResolution
				+ (uint)PixelCell.z * CellResolution * CellResolution;
		
		// Go through all surfels in grid cell
		uint EntryCount = min(GridCounter[CellIdx], CellCapacity);
		
		float CoverageWeight = 0.f;		
		for (uint i = 0; i < EntryCount; i++)            
		{                         
			int SurfelIdx = GridCellEntries[CellIdx * CellCapacity + i];
			
			// Retrieve Surfel
			float3 Position = SurfelPositionAndRadius[SurfelIdx].xyz;
			float Radius = SurfelPositionAndRadius[SurfelIdx].w;
			float3 Normal = normalize(SurfelNormalAndFlags[SurfelIdx].xyz);
			
			// Check how close the surfel center is to this world position
			// Farther surfels add more coverage than closer ones
			float Distance =  length(WorldPositionAtPixel - Position);
			
			// Discard ones outside the radius or farther
			float DistanceWeight = 1.0f - smoothstep(0.0f, Radius, Distance);
			
			// Dot product normals to see if the surfel is aligned with the surface
			// It may be that the surface is sharp so the surfel belongs to another surface
			float NormalsFacingFactor = saturate(dot(Normal, WorldNormalAtPixel));
			
			// Final Surfel Weight
			float FinalSurfelWeight = Distance * NormalsFacingFactor;
			
			// Add to final coverage weight
			CoverageWeight += FinalSurfelWeight;
		}         
		
		// Store coverage into the texture
		CoverageTexture[PixelPos] = CoverageWeight;
	}
}